# You are given two strings s and t.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Return the letter that was added to t.

class Solution:
    def findTheDifference(self,s,t):
        for ch in t:
            if ch not in s:
                return ch
            else:
                s = s.replace(ch, '', 1)

s_obj = Solution()
print(s_obj.findTheDifference("abcd","abcde"))
print(s_obj.findTheDifference("","y"))
